# Generated by Django 2.2 on 2022-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Username :')),
                ('password', models.CharField(max_length=25, verbose_name='Password :')),
                ('rights', models.CharField(max_length=25)),
            ],
        ),
    ]
