# Generated by Django 2.2 on 2022-02-14 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='date of birth')),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
