# Generated by Django 2.2 on 2022-02-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('comm', models.IntegerField()),
                ('dept', models.CharField(max_length=25)),
            ],
        ),
    ]
