# Generated by Django 2.2 on 2022-02-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
    ]
