# Generated by Django 4.0.3 on 2022-03-08 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptReg',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username : ')),
                ('password', models.CharField(max_length=15, verbose_name='Password : ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email :')),
                ('department', models.CharField(max_length=30, verbose_name='Department : ')),
                ('panchayath', models.CharField(max_length=30, verbose_name='Enter your panchayath : ')),
                ('district', models.CharField(max_length=30, verbose_name='Enter your district : ')),
                ('state', models.CharField(max_length=30, verbose_name='Enter your state : ')),
                ('country', models.CharField(max_length=30, verbose_name='Enter your country ')),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username : ')),
                ('password', models.CharField(max_length=15, verbose_name='Password : ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email :')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="phone number must be entered in the format: '+91'. Up to 12 digital allowed.", regex='^\\+?1?\\d{9,12}$')], verbose_name='Phone number :')),
                ('panchayath', models.CharField(max_length=30, verbose_name='Enter your panchayath : ')),
                ('district', models.CharField(max_length=30, verbose_name='Enter your district : ')),
                ('state', models.CharField(max_length=30, verbose_name='Enter your state : ')),
                ('country', models.CharField(max_length=30, verbose_name='Enter your country ')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name : ')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name : ')),
                ('house_name', models.CharField(max_length=50, verbose_name='House Name : ')),
                ('house_number', models.IntegerField(verbose_name='House Number : ')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender : ')),
                ('dob', models.DateField(verbose_name='Date of Birth : ')),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
