# Generated by Django 4.0.3 on 2022-03-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_deptreg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReg',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username : ')),
                ('password', models.CharField(max_length=15, verbose_name='Password : ')),
                ('status', models.CharField(default='new Admin', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='deptreg',
            name='status',
            field=models.CharField(default='new department', max_length=20),
        ),
    ]
