# Generated by Django 4.0.3 on 2022-03-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post_delete_adminreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creatorid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
