# Generated by Django 4.0.3 on 2022-03-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_post_id_post_image_alter_post_creatorid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='pimage',
            field=models.ImageField(default='x', upload_to='images/'),
        ),
    ]
