# Generated by Django 4.0.3 on 2022-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_vote_post_downvote_post_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvotestatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotestatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='downvotestatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='upvotestatus',
            field=models.IntegerField(default=0),
        ),
    ]
