# Generated by Django 4.0.3 on 2022-03-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post_downvotestatus_post_upvotestatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='creatorid',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvotestatus',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotestatus',
        ),
    ]
