# Generated by Django 4.0.3 on 2022-04-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uname',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
