# Generated by Django 4.0.3 on 2022-04-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messageid',
            new_name='mid',
        ),
    ]
