# Generated by Django 4.0.3 on 2022-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_messageid_message_mid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('uname', models.CharField(max_length=30)),
                ('complaint', models.TextField(max_length=300)),
            ],
        ),
    ]
