# Generated by Django 4.0.3 on 2022-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='panchayath',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
